"""ARIA Prompts Module"""
from prompts.research_prompts import RESEARCH_SYSTEM_PROMPT, RESEARCH_REASONING_PROMPT
from prompts.creative_prompts import CREATIVE_SYSTEM_PROMPT, CREATIVE_WRITING_PROMPT
from prompts.technical_prompts import (
    TECHNICAL_SYSTEM_PROMPT,
    TECHNICAL_ANALYSIS_PROMPT,
    CODE_VALIDATION_PROMPT
)

__all__ = [
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_REASONING_PROMPT",
    "CREATIVE_SYSTEM_PROMPT",
    "CREATIVE_WRITING_PROMPT",
    "TECHNICAL_SYSTEM_PROMPT",
    "TECHNICAL_ANALYSIS_PROMPT",
    "CODE_VALIDATION_PROMPT"
]
