"""Prompts module"""
from src.prompts.research_prompts import (
    RESEARCH_SYSTEM_PROMPT,
    RESEARCH_INITIAL_PROMPT,
    RESEARCH_FOLLOW_UP_PROMPT,
    RESEARCH_REASONING_PROMPT
)
from src.prompts.creative_prompts import (
    CREATIVE_SYSTEM_PROMPT,
    CREATIVE_WRITING_PROMPT,
    CREATIVE_IDEATION_PROMPT,
    CREATIVE_REASONING_PROMPT
)
from src.prompts.technical_prompts import (
    TECHNICAL_SYSTEM_PROMPT,
    TECHNICAL_ANALYSIS_PROMPT,
    TECHNICAL_OPTIMIZATION_PROMPT,
    TECHNICAL_REASONING_PROMPT,
    CODE_VALIDATION_PROMPT
)

__all__ = [
    # Research
    "RESEARCH_SYSTEM_PROMPT",
    "RESEARCH_INITIAL_PROMPT",
    "RESEARCH_FOLLOW_UP_PROMPT",
    "RESEARCH_REASONING_PROMPT",
    # Creative
    "CREATIVE_SYSTEM_PROMPT",
    "CREATIVE_WRITING_PROMPT",
    "CREATIVE_IDEATION_PROMPT",
    "CREATIVE_REASONING_PROMPT",
    # Technical
    "TECHNICAL_SYSTEM_PROMPT",
    "TECHNICAL_ANALYSIS_PROMPT",
    "TECHNICAL_OPTIMIZATION_PROMPT",
    "TECHNICAL_REASONING_PROMPT",
    "CODE_VALIDATION_PROMPT"
]